//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACKING_SYSTEM_LINES
    {
        public string HEADER_TRACKING_NUM { get; set; }
        public System.DateTime PROCESSING_DATE { get; set; }
        public string IMPLEMENTATION_STATUS { get; set; }
        public string CUSTOMER_REPLY { get; set; }
        public System.DateTime ASSIGN_PEOPLE { get; set; }
        public string TRACKING_LINE_NUM { get; set; }
        public decimal ISDELETED { get; set; }
    
        public virtual TRACKING_SYSTEM_HEADS TRACKING_SYSTEM_HEADS { get; set; }
    }
}
