//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACKING_SYSTEM_HEADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRACKING_SYSTEM_HEADS()
        {
            this.TRACKING_SYSTEM_LINES = new HashSet<TRACKING_SYSTEM_LINES>();
        }
    
        public string TRACKING_NUM { get; set; }
        public string TRACKING_TYPE { get; set; }
        public string CUSTOMER_TYPE { get; set; }
        public string REQUESTER { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public string PRIORITY_LEVEL { get; set; }
        public System.DateTime DEADLINE { get; set; }
        public string TRACKING_CONTENT { get; set; }
        public string ASSIGN_PEOPLE { get; set; }
        public string CASE_STATE { get; set; }
        public Nullable<System.DateTime> CLOSING_DATE { get; set; }
        public decimal ISDELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACKING_SYSTEM_LINES> TRACKING_SYSTEM_LINES { get; set; }
    }
}
